services:

  clickhouse:
    image: clickhouse:latest
    container_name: clickhouse
    network_mode: host
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    volumes:
      - ./clickhouse/config.d/:/etc/clickhouse-server/config.d/
      - ./clickhouse/user.d/:/etc/clickhouse-server/users.d/
      - ./clickhouse/log:/var/log/clickhouse-server/
      #- ./clickhouse/data:/var/lib/clickhouse/
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 6000M

  jupyter:
    image: jupyter/local
    container_name: jupyter
    volumes:
      - ../jupyter/notebooks:/home/jovyan/work
      - ../jupyter/connections.ini:/home/jovyan/.jupysql/connections.ini
    network_mode: host
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
