services:
  kafka-test:
    image: kafka/jmx
    container_name: kafka_test
    network_mode: host
    ports:
      - 9092:9092
      - 7071:7071
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      #KAFKA_ADVERTISED_PORT: 9092
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
